### ISSUE TITLE
When it will be released?

### ISSUE THREAD

**Issue by jfbaquerocelis** [MartinMalinda/ember-timerange-picker#1]
Hi, I am really waiting the released of this addon. It is just that I need. Regards! :relaxed:

**Comment by MartinMalinda** [comment]
Hello, as of now, most features  are functioning and addon is released on npm. `ember install ember-timerange-picker` should work although I haven't tested (I have it installed directly from Github in my app). 

The only issue is Ember Observer still lists this a WIP.

Feel free to report here if you have any issues with the addon.

**Comment by jfbaquerocelis** [comment]
Cool, I'll report in that case. Thanks and Blessings!
